name: Build docker image
on: [push]
jobs:
  Build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build \
            --file docker/Dockerfile \
            --tag yasl \
            .
