---
name: Build pipeline
on: [push]
jobs:
  Run-go-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'

      - name: Run tests
        run:
          go test
            -coverpkg=code.gitizy.dev/yasl/...
            -coverprofile=coverage.out
            ./...

      - name: Display coverage percentages
        run: go tool cover -func=coverage.out

      - name: Generate coverage HTML report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Archive coverage HTML report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          if-no-files-found: error
          path: coverage.html

  Docker-image:
    runs-on: ubuntu-20.04
    needs: Run-go-tests
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Build docker image
        run:
          docker build
            --file docker/Dockerfile
            --tag gitizy/yasl:${{ github.sha }}
            .

      - name: Edit an action.yml file for test local build
        run:
          "sed -i 's@image:.*@image: gitizy/yasl:${{ github.sha }}@' action.yml"

      - name: Test the local action
        uses: ./
